apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-web-rules
  namespace: web
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: tripviewer-frontend
          servicePort: 8080
        path: /(?!api)[a-z0-9]+$
---
