apiVersion: v1
kind: Pod
metadata:
  name: demo
  namespace: api
  labels:
    aadpodidbinding: apiidentity
spec:
  containers:
  - name: demo
    image: mcr.microsoft.com/oss/azure/aad-pod-identity/demo:v1.6.3
    args:
      - --subscriptionid=1a7a95d7-122f-4920-a3cb-b47515acefc9
      - --clientid=ba17a587-bb5f-4e85-904d-1fb4388f294f
      - --resourcegroup=teamResources
    env:
      - name: MY_POD_NAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: MY_POD_NAMESPACE
        valueFrom:
          fieldRef:
            fieldPath: metadata.namespace
      - name: MY_POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
  nodeSelector:
    kubernetes.io/os: linux
