apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname
  namespace: api
spec:
  provider: azure   
  parameters:
    usePodIdentity: "true"
    tenantId: "c5d948ca-43a4-4629-8958-e1ec31d8c3f7"
    subscriptionId: "1a7a95d7-122f-4920-a3cb-b47515acefc9"
    resourceGroup: "teamResources"
    keyvaultName: "team4akskv"
    objects: |
      array:
        - |
          objectName:  SQL-PASSWORD
          objectType:  secret
          objectAlias: SQL_PASSWORD
        - |
          objectName: SQL-USER
          objectType: secret
          objectAlias: SQL_USER
        - |
          objectName: SQL-SERVER
          objectType: secret
          objectAlias: SQL_SERVER           
        - |
          objectName: SQL-DBNAME
          objectType: secret 
          objectAlias: SQL_DBNAME
