apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
    name: "team4tripviewer-agentpool"               # The name of your Azure identity
spec:
    type: 0                                 # Set type: 0 for managed service identity
    resourceID: /subscriptions/1a7a95d7-122f-4920-a3cb-b47515acefc9/resourcegroups/MC_teamResources_team4tripviewer_northeurope/providers/Microsoft.ManagedIdentity/userAssignedIdentities/team4tripviewer-agentpool
    clientID: "8917dd75-810f-45bf-a090-49321b4d4175"     # The clientId of the Azure AD identity that you created earlier
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
    name: azure-pod-identity-binding
spec:
    azureIdentity: "team4tripviewer-agentpool"      # The name of your Azure identity
    selector: azure-pod-identity-binding-selector
